### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/rustybuzz#138]
Due to various reasons I will no longer be able to maintain this project. This includes even minor staff like accepting PRs and pushing releases. 
Therefore I would like to transfer ownership to someone else, which would be a better choice than simply archiving it.
This includes giving an access to this repo + cargo.

@LaurenzV @laurmaedje 

@behdad are you still interested in moving this library under the `harfbuzz` project umbrella?
This includes `ttf-parser` as well, since they are inseparable as of now.

Also, some people from google/fontations wanted to fork this project (can't find the discussion for some reason). Now is the time.

**Comment by LaurenzV** [comment]
The fork already exists: https://github.com/harfbuzz/harfruzz

Although it's a bit outdated by now.

**Comment by RazrFalcon** [comment]
Huh... I didn't knew that. Well, even better then.

Still, someone would have to maintain this project for a while, assuming `harfruzz` would be finished eventually.
@LaurenzV Would you be interested in taking ownership of this repo?

**Comment by LaurenzV** [comment]
Let’s maybe wait what the others have to say.

**Comment by behdad** [comment]
I think it's okay to move them to harfbuzz/ organization, as long as @LaurenzV updates it (and @dfrg updates HarfRuzz downstream from it).

**Comment by LaurenzV** [comment]
I would try my best to keep it updated at least until harfruzz is ready! 

After that, I think it would be best to archive, though, as there isn’t much point in keeping two versions around, if that’s okay with @RazrFalcon

**Comment by behdad** [comment]
I talked to other harfbuzz org admins and we would be happy to have these two repositories there. @RazrFalcon Feel free to transfer to harfbuzz org or to me and I'll do, don't know which is easier.

**Comment by RazrFalcon** [comment]
@behdad Thanks a lot! I appreciate that.

Seems like I need to be a part of the organization to move to it.

>Transfer this repository to another user or to an organization where you have the ability to create repositories.

>You don’t have the permission to create public repositories on harfbuzz

Can you add and remove me to the org? Or should I try moving to you first?

**Comment by alerque** [comment]
I would also suggest moving it to the harfbuzz namespace. I can help out with release management and stuff like that if needed/desired.

**Comment by alerque** [comment]
Don't do an intermediate move on the way to it's intended home, the GH redirects will get messed up were any of the parties to fork the repo at a later date.

**Comment by behdad** [comment]
@RazrFalcon Lemme add you to the org. You are welcome to hang out there. :)

**Comment by behdad** [comment]
> @RazrFalcon Lemme add you to the org. You are welcome to hang out there. :)

Done.

**Comment by RazrFalcon** [comment]
https://github.com/harfbuzz/rustybuzz 🎉 

Thanks a lot again.

I agree with @LaurenzV here. This repo is sort of finished. All it needs is backporting changes form time to time, publishing releases and keeping it alive in general. 
At least until `harfruzz` will be good enough to replace it. And then it could be actually archived. Unless someone would prefer it to `harfruzz` for whatever reason.

I've sent crates.io invitations as well. @behdad do you have crates.io account? Or who I can invite from the harfuzz project to it?

**Comment by RazrFalcon** [comment]
@alerque 

>Don't do an intermediate move on the way to it's intended home, the GH redirects will get messed up were any of the parties to fork the repo at a later date.

Yes, I never transferred projects before, so I'm not sure what roadblocks we would have. Updating links in the readme and Cargo.toml are probably the fist task.

**Comment by behdad** [comment]
> I've sent crates.io invitations as well. @behdad do you have a crates.io account? Or who I can invite from the harfbuzz project to it?

No I'm not into the Rust ecosystem. @alerque or @khaledhosny would be best I think.

**Comment by RazrFalcon** [comment]
Done.

**Comment by RazrFalcon** [comment]
@LaurenzV Do you still have access to this repo? Or should you be added to harfbuzz project first?

**Comment by behdad** [comment]
> @LaurenzV Do you still have access to this repo? Or should you be added to harfbuzz project first?

They have as far as I see in the settings.

**Comment by LaurenzV** [comment]
Yeah, I think I can!

> Done.

ttf-parser is still missing, right?

**Comment by RazrFalcon** [comment]
Oh right, not sure if `ttf-parser` should be part of harfbuzz project. We can keep it separate for now.

**Comment by khaledhosny** [comment]
> > I've sent crates.io invitations as well. @behdad do you have a crates.io account? Or who I can invite from the harfbuzz project to it?
> 
> No I'm not into the Rust ecosystem. @alerque or @khaledhosny would be best I think.

https://crates.io/users/khaledhosny

**Comment by laurmaedje** [comment]
Thanks @RazrFalcon for the graceful transfer and everybody else for keeping the lights on!

If anything else needs help, e.g. maintainance of ttf-parser (no matter whether moved or not), I could also help with that.

**Comment by alerque** [comment]
@khaledhosny/@LaurenzV or somebody, my permissions on harfbuzz and even on the org here did extend to this repo when it got migrated it. This repo must have individual instead of org or team permissions set. Can somebody add me here too? Thanks.

**Comment by behdad** [comment]
> @khaledhosny/@LaurenzV or somebody, my permissions on harfbuzz and even on the org here did extend to this repo when it got migrated it. This repo must have individual instead of org or team permissions set. Can somebody add me here too? Thanks.

I added you as a maintainer.

**Comment by RazrFalcon** [comment]
@behdad any chance we can move [ttf-parser](https://github.com/RazrFalcon/ttf-parser) under the harfbuzz umbrella as well? It's a core part of `rustybuzz` after all.

**Comment by behdad** [comment]
> @behdad any chance we can move [ttf-parser](https://github.com/RazrFalcon/ttf-parser) under the harfbuzz umbrella as well? It's a core part of `rustybuzz` after all.

Yes, feel free to move.

**Comment by RazrFalcon** [comment]
Done, thanks again!
