### ISSUE TITLE
Review indexing from intergers to make sure we don't allow unintentional overflows

### ISSUE THREAD

**Issue by alerque** [harfbuzz/rustybuzz#145]
> There are a few other instances of this exact construct as well as a large number of `as` invocations on integer types that are not very safe or idiomatic. That doesn't necessarily mean it is even possible to trigger other issues like this one, but it does mean there could be a little more defensive coding here.

_Originally posted by @alerque in https://github.com/harfbuzz/rustybuzz/issues/142#issuecomment-2466185116_

I did a quick pass looking for other potential instances of similar overflows and see a few potential cases. I did not review the larger context to figure out whether the potential overflow is a reachable code path, only the local context of the integer handling.

Unfortunately in playing with "fixing" these it became obvious the cases are not all covered by existing test. For example one can delete this line of code entirely and the test suite still just passes:

https://github.com/harfbuzz/rustybuzz/blob/7386be4e50167e36657e1cd3cb7083d2389202a1/src/hb/ot_layout_gsubgpos.rs#L941

**Comment by behdad** [comment]
See https://github.com/harfbuzz/rustybuzz/issues/142#issuecomment-2466333588

**Comment by alerque** [comment]
Reopened #142 for tracking, all discussion is there.
